name: python-study
channels:
- conda-forge
- defaults
dependencies:
- numpy=1.14.0
- pip=9.0.1
- python=3.6.4
- requests=2.19.1
- statsmodels=0.9.0
- nb_conda=2.2.1
- ipykernel=4.8.2
- matplotlib=2.2.3
- scipy=1.1.0
- pip:
  - logbook==1.2.1
  - pandas==0.23.4
  - pykalman==0.9.5